name: Deploy Frontend

# Trigger only on pushes to main (or your branch) 
# AND only if files in the client folder changed
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install packages and build
        working-directory: client
        env:
          VITE_SERVER_URL: ${{ secrets.PROD_SERVER_URL }}
        run: |
          npm ci
          npm run build
      - name: Deploy Frontend
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
          cname: nousdb.com
